_core:
  default_config_hash: l58O_yEXSo-SeJi19LXdzTU1tNJG3lmnIhCitRkM1tk
langcode: en
uuid: 7073b6ab-71a8-44f4-a8ad-a38528d9be1a
name: 'coffe shop'
mail: lisastina.hansson@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /user/login
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
